"""add picture_url to Cookie

Revision ID: 4ca25f02be72
Revises: 147250a40912
Create Date: 2023-03-27 22:34:08.991345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca25f02be72'
down_revision = '147250a40912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cookie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(length=260), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cookie', schema=None) as batch_op:
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
